CREATE TABLE users (
	id SERIAL NOT NULL PRIMARY KEY,
	username VARCHAR(500) UNIQUE NOT NULL,
	fullname VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(200) NOT NULL,
	phone VARCHAR(10) UNIQUE NOT NULL,
	avatar TEXT,
	location TEXT,
	coordinates TEXT,
	created_at TIMESTAMP DEFAULT NOW()
);