version: '3.9'

services:
  redis:
    build: ./redis/.
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - .cache:/data
    
  golang:
    container_name: golang_container
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - redis

volumes:
  redis: {}