version: '3.9'

services:
  redis:
    build: ./redis/.
    container_name: redis_container
    ports:
      - 6379:6379
    restart: on-failure
    volumes:
      - .cache:/data
    
  golang:
    container_name: golang_container
    build:
      dockerfile: Dockerfile.local
    ports:
      - 8080:8080
    # For Local
    volumes:
      - ./:/app
    restart: on-failure
    depends_on:
      - redis

volumes:
  redis: {}